-- 나의 풀이 1
SELECT A.NAME 
FROM (SELECT MIN(DATETIME), NAME
     FROM ANIMAL_INS) A

-- 나의 풀이 2
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS)

-- 다른사람 풀이
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 알게된 점
-- MySQL에서는 LIMIT 1 을 통해 하나의 행을 가져올 수 있다